### ISSUE TITLE
Saving campaign without logging in

### ISSUE THREAD

**Issue by nanometer34688** [PaulleDemon/Email-automation#1]
Hi,

This software looks great! 

I am deploying locally and would like to produce email campaigns without the need to sign up to your site.

Is there a way to do this?

Thanks

**Comment by PaulleDemon** [comment]
Hi @nanometer34688, If you are deploying locally you are not signing up to my site, your data is not sent to my servers its instead saved locally. If you want to remove the login part you will have to make a lot of changes to the code.  You can also create a dummy email for signing up such as `example@dummymail.com` from the admin panel and log in.

If you have any further questions let me know.
