### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by nanometer34688** [PaulleDemon/Email-automation#3]
Hi,

Is it possible to have a docker version of this? 

I have been able to get the UI working after running both `python manage.py migrate` and `python manage.py runserver`.

Having to build the redis server manually as well as running the other commands above, it would be beneficial to have this deployed within a docker-compose.yaml file 

Is there any reason why that would not work?

**Comment by nanometer34688** [comment]
I have experience with docker and I can help make this for you as I think this is great software! 

I am currently having issues with tailwind. See here for my error: https://github.com/PaulleDemon/Email-automation/issues/2

**Comment by nanometer34688** [comment]
I have experience with docker and I can help make this for you as I think this is great software!

**Comment by PaulleDemon** [comment]
You can surely dockerize this project for your personal use. I see no reason not to.
